[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.18.2"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.13.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.1"

[prune]
  go-tests = true
  unused-packages = true
